## ------------------------------------------------------------------------------
## benchmark shortname
## ------------------------------------------------------------------------------
id: longread_germline_structural_variant_calling_benchmark

## ------------------------------------------------------------------------------
## benchmark description
## ------------------------------------------------------------------------------
description: Long read germline structural variant calling benchmarking

## ------------------------------------------------------------------------------
## Benchmark version. `1.0`.
## ------------------------------------------------------------------------------
version: 1.0

## ------------------------------------------------------------------------------
## Benchmark builder/contact person
## ------------------------------------------------------------------------------
benchmarker: "Monica Aguila i Sans, monica.aguila.i.sans@regionh.dk"

## ------------------------------------------------------------------------------
## Benchmark YAML schema/specification version. Currently `0.01`.
## ------------------------------------------------------------------------------
benchmark_yaml_spec: 0.01

## ------------------------------------------------------------------------------
## The software backend used to run the benchmark
## ------------------------------------------------------------------------------
software_backend: apptainer

## ------------------------------------------------------------------------------
## Software environment recipes associated to this benchmark.
## ------------------------------------------------------------------------------
software_environments:
  Python:
    description: "Python v.3.12.10"
    apptainer: ./containers/python/python_3.12.10-numpy_2.2.5-pandas_2.2.3__v0.1__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  CuteSV:
    description: "CuteSV"
    apptainer: ./containers/cutesv/cutesv_2.1.3__v2.0__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  DeBreak:
    description: "DeBreak v.1.2.0"
    apptainer: oras://quay.io/moniagsa/debreak:3.0
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Delly2:
    description: "Delly2 v1.7.2"
    apptainer: ./containers/delly2/delly2_1.7.2__v2.0__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Dysgu:
    description: "Dysgu"
    apptainer: ./containers/dysgu/dysgu_1.8.7__v3.0__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Kled:
    description: "Kled"
    apptainer: ./containers/kled/kled_1.2.10__v1.3__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  PAV:
    description: "PAV"
    apptainer: ./containers/pav/pav_2.4.6__v1.40__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Sawfish2:
    description: "Sawfish v2.2.1"
    apptainer: ./containers/sawfish/sawfish_2.2.1__v1.0__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Severus:
    description: "Severus v.1.6.0"
    apptainer: ./containers/severus/severus_1.6__v1.0__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Sniffles2:
    description: "Sniffles2 v.2.7.1"
    apptainer: ./containers/sniffles2/sniffles2_2.7.1__v1.3__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  SVIM:
    description: "SVIM v2.0.0"
    apptainer: ./containers/svim/svim_2.0.0__v1.1__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  SVision:
    description: "SVision v1.4"
    apptainer: ./containers/svision/svision_1.4__2.3__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Truvari:
    description: "Truvari v5.3.0"
    apptainer: ./containers/truvari/truvari_5.3.0_python_3.10_python_3.12__v1.0__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  Bcftools-samtools:
    description: "Bcftools v1.22 with Samtools v1.22"
    apptainer: ./containers/samtools/bcftools_1.22_samtools_1.22-htslib_1.22-python3.12__v2.0__.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file
  VGcall:
    description: "VG call v1.68"
    apptainer: ./containers/vg/vg_1.68.0-py312.sif
    conda: ./fake_envs/R.yml  # This is expected to be present, but it can just be an empty file

metric_collectors:
  - id: truvari-consistency-ins
    name: "Truvari-consistency-ins"
    software_environment: "Truvari"
    repository:
      url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-truvari-consistency.git
      commit: 7c83335
    inputs:
      - split-types.ins.vcf.gz
    outputs:
      - id: truvari-consistency-ins-test.consistency.flag
        path: "{input}/truvari_consistency.ins.flag"
  - id: truvari-consistency-del
    name: "Truvari-consistency-del"
    software_environment: "Truvari"
    repository:
      url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-truvari-consistency.git
      commit: 7c83335
    inputs:
      - split-types.del.vcf.gz
    outputs:
      - id: truvari-consistency-del.consistency.flag
        path: "{input}/truvari_consistency.del.flag"
  - id: truvari-consistency-inv
    name: "Truvari-consistency-inv"
    software_environment: "Truvari"
    repository:
      url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-truvari-consistency.git
      commit: 7c83335
    inputs:
      - split-types.inv.vcf.gz
    outputs:
      - id: truvari-consistency-inv.consistency.flag
        path: "{input}/truvari_consistency.inv.flag"

stages:
  - id: data
    modules:
      - id: NA12877.GRCh38.haplotagged
        name: "Collect input bams"
        software_environment: "Python"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-data-input.git
          commit: 3e7b355
      - id: NA12878.GRCh38.haplotagged
        name: "Collect input bams"
        software_environment: "Python"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-data-input.git
          commit: 3e7b355
      - id: NA12879.GRCh38.haplotagged
        name: "Collect input bams"
        software_environment: "Python"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-data-input.git
          commit: 3e7b355
      - id: NA12881.GRCh38.haplotagged
        name: "Collect input bams"
        software_environment: "Python"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-data-input.git
          commit: 3e7b355
      - id: NA12882.GRCh38.haplotagged
        name: "Collect input bams"
        software_environment: "Python"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-data-input.git
          commit: 3e7b355
      - id: NA12885.GRCh38.haplotagged
        name: "Collect input bams"
        software_environment: "Python"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-data-input.git
          commit: 3e7b355
      - id: NA12886.GRCh38.haplotagged
        name: "Collect input bams"
        software_environment: "Python"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-data-input.git
          commit: 3e7b355
    outputs:
      - id: data.linear.bam
        path: "{dataset}.linear.bam"
      - id: data.linear.bam.bai
        path: "{dataset}.linear.bam.bai"
      - id: data.graph.bam
        path: "{dataset}.graph.bam"
      - id: data.graph.bam.bai
        path: "{dataset}.graph.bam.bai"
      - id: data.gam
        path: "{dataset}.gam"
      - id: data.asm.hap1
        path: "{dataset}.asm.bp.hap1.p_ctg.gfa"
      - id: data.asm.hap2
        path: "{dataset}.asm.bp.hap2.p_ctg.gfa"
      - id: data.truthset
        path: "{dataset}.truthset.vcf.gz"
      - id: data.truthset.tbi
        path: "{dataset}.truthset.vcf.gz.tbi"
      - id: data.reference
        path: "{dataset}.reference.fasta"
      - id: data.reference.fai
        path: "{dataset}.reference.fasta.fai"

  - id: variant_calling
    modules:
      - id: cutesv
        name: "Variant calling with CuteSV"
        software_environment: "CuteSV"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-variant-calling-cutesv.git
          commit: 9ea4a23
        parameters:
          - values: ["--workflow", "linear"]
          - values: ["--workflow", "graph"]
      - id: debreak
        name: "Variant calling with DeBreak"
        software_environment: "DeBreak"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-variant-calling-debreak.git
          commit: 1e9e332
        parameters:
          - values: ["--workflow", "linear"]
          - values: ["--workflow", "graph"]
      - id: delly2
        name: "Variant calling with Delly2"
        software_environment: "Delly2"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-variant-calling-delly2.git
          commit: 631ff2d
        parameters:
          - values: ["--workflow", "linear"]
          - values: ["--workflow", "graph"]
      - id: dysgu
        name: "Variant calling with Dysgu"
        software_environment: "Dysgu"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-variant-calling-dysgu.git
          commit: 79d960b
        parameters:
          - values: ["--workflow", "linear"]
          - values: ["--workflow", "graph"]
    inputs:
      - entries:
        - data.linear.bam
        - data.linear.bam.bai
        - data.graph.bam
        - data.graph.bam.bai
        - data.gam
        - data.asm.hap1
        - data.asm.hap2
        - data.truthset
        - data.truthset.tbi
        - data.reference
        - data.reference.fai
    outputs:
      - id: variant_calling.vcfs
        path: "{dataset}.vcf"

  - id: vcf-postprocessing  
    modules:
      - id: Postprocessing
        name: "Postprocessing"
        software_environment: "Bcftools-samtools"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-vcf-postprocessing.git
          commit: b54ccfd
    inputs:
      - entries: variant_calling.vcfs
    outputs:
      - id: variant_calling.vcfs.gz
        path: "{dataset}.vcf.gz"

  - id: truvari
    modules:
      - id: Truvari
        name: "Truvari"
        software_environment: "Truvari"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-truvari-bench.git
          commit: 3ba80fa
    inputs:
      - entries: 
        - variant_calling.vcfs.gz
        - data.truthset
        - data.reference
    outputs:
      - id: variant_calling_metrics.fp
        path: "{dataset}.fp.vcf.gz"
      - id: variant_calling_metrics.fn
        path: "{dataset}.fn.vcf.gz"
      - id: variant_calling_metrics.tp
        path: "{dataset}.tp-base.vcf.gz"
      - id: variant_calling_metrics.tp.tbi
        path: "{dataset}.tp-base.vcf.gz.tbi"
      - id: variant_calling_metrics.summary
        path: "{dataset}.summary.json"

  - id: split-types-ins
    modules:
      - id: Split-types-ins
        name: "split-types-ins"
        software_environment: "Bcftools-samtools"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-split-svtypes.git
          commit: 188f1bc
        parameters:
          - values: ["--sv_type", "INS"]
    inputs:
      - entries: 
        - variant_calling_metrics.tp
        - variant_calling_metrics.tp.tbi
    outputs:
      - id: split-types.ins.vcf.gz
        path: "{dataset}.INS.tp-base.vcf.gz"

  - id: split-types-inv
    modules:
      - id: Split-types-inv
        name: "split-types-inv"
        software_environment: "Bcftools-samtools"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-split-svtypes.git
          commit: 188f1bc
        parameters:
          - values: ["--sv_type", "INV"]
    inputs:
      - entries: 
        - variant_calling_metrics.tp
        - variant_calling_metrics.tp.tbi
    outputs:
      - id: split-types.inv.vcf.gz
        path: "{dataset}.INV.tp-base.vcf.gz"

  - id: split-types-del
    modules:
      - id: Split-types-del
        name: "split-types-del"
        software_environment: "Bcftools-samtools"
        repository:
          url: https://github.com/cphgeno/OB_LONGREAD_GERMLINE_SV_CALLERS_BENCHMARK-split-svtypes.git
          commit: 188f1bc
        parameters:
          - values: ["--sv_type", "DEL"]
    inputs:
      - entries: 
        - variant_calling_metrics.tp
        - variant_calling_metrics.tp.tbi
    outputs:
      - id: split-types.del.vcf.gz
        path: "{dataset}.DEL.tp-base.vcf.gz"

